### PR TITLE
changed to use new fixer.io api (old one was deprecated) 

### PR DESCRIPTION
**Pull request by tannercorbin**
Hey all, this is the first time I've ever contributed or done a pull request so please let me know if I missed anything or didn't follow standards.  

The master branch was using a deprecated API from fixer.io and therefore not working.  I updated the code to use the api, but it now requires an api-key.  So I made it so we grab an api key from the config file.

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @tannercorbin, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @tannercorbin!

Thank you for signing the Singer Contribution License Agreement.

**Comment by timvisher** [comment]
Thanks for contributing, @tannercorbin!

@dmosorast Had actually taken a shot at this exact same patch a few weeks ago and was unable to get past a few API issues. Maybe they've gone away now? [Here](https://github.com/singer-io/tap-fixerio/compare/master...dmosorast:fix/add-api-key) was his attempt.

Can you provide logs that show this working? A gist would work.

**Comment by dmosorast** [comment]
To elaborate a bit, I ran into the first `https_access_restricted` error and added handling for it, then got the error `base_currency_access_restricted` mentioned [here](https://github.com/fixerAPI/fixer/issues/109).

Looking at the [new APIs error listing](https://fixer.io/documentation#errors) along with the base curency issue not listed in that page, it looked like it would be much more complicated than I originally anticipated, so I switched to [exchangeratesapi.io](https://exchangeratesapi.io/), which is feature compatible with Fixer's old API.

**Comment by tannercorbin** [comment]
Thanks guys.  @dmosorast - I noticed the same thing with the base currency issue, but didn't even consider handling the other API error.  Your code works as long as you have EUR base currency or use a paid account api key.  
Here's a [gist](https://gist.github.com/tannercorbin/ef896d743934a600cd735b6dca4a56d9) to show the output.

Again, this was my first time to try to contribute to a project so I learned a lot.  How could I have known that @dmosorast already took a shot at this to avoid retracing his work?  Any advice would be greatly appreciated.

Thanks!

**Comment by timvisher** [comment]
@tannercorbin This is looking good!

Can you update the README with setup instructions. Where do I go to get a Fixer.io API key? Tell me about the `config.sample.json` file, what its keys mean, and how I can run the tap with it.

Also, please get a `Development` section in documenting the use of virtualenvs. Something along [these lines](https://github.com/singer-io/singer-tap-template/issues/3).

--------------------

Regarding finding @dmosorast's work, honestly there's no great way to do it. One thing you can usually try is to use the [`Insights → Network`](https://github.com/singer-io/tap-fixerio/network) page of the project to see if there's anything interesting going on, but honestly that only works on moderately inactive projects like this one. If there's a large number of forks or a very active development community then digesting that can be pretty difficult.

Another thing you can try is to submit an Issue before you work on the code. The maintainers of the project are often more aware of significant work being done on the project than you could possibly be, especially in the case of high-volume contribution projects. So making your first action nice and cheap ("Hey, I'm interested in fixing X, is anyone else already working on that?") can free you up or get you pointed in the right direction.

**Comment by briansloane** [comment]
We're going to close this issue. Feel free to reopen if you make the suggested changes.

**Pull request closed without merging**
