### PR TITLE
Enhancement: Allow optional list of currencies to be specified in config

### PR DESCRIPTION
**Pull request by haaspt**
This is a small modification I added for my own purposes, it adds the option to set a list of `symbols` in the config file which is then passed in the Fixer request. The value defaults to None so it doesn't require any changes to existing config files.

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @haaspt, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @haaspt!

Thank you for signing the Singer Contribution License Agreement.

**Comment by timvisher** [comment]
I like the change to the sample config but I think the best thing would be to add a table to the README file. Something to the effect of:

| Config Key | Required? | Default | Description | 
| --- | --- | --- | --- |
| `base` | Yes | None | ??? |
| `start_date` | Yes | ??? | ??? date in UTC |
| etc. | | | |

**Comment by haaspt** [comment]
I added this table to README.md:

Config Key | Required? | Default | Description
--- | --- | --- | ---
`base` | Yes | 'USD' | The base rate to which others will be converted
`start_date` | Yes | Today | The starting date from which rates will be pulled in `YYYY-MM-DD` format (overridden if a state file is passed)
`access_key` | Yes | None | Your fixer.io access key
`symbols` | No | None | An optional list of currency symbols to fetch in the following format: ['USD', 'GBP', etc.]. If not specified fixer will return a list of all exchange rates for each day

**Pull request merged**
